### ISSUE TITLE
llama-magic: "workflow" or primer?

### ISSUE THREAD

**Issue by sklages** [FenyoLab/llama-magic#1]
Hi,
I wanted to use llama-magic without setting up a webserver. I want to use it locally on linux systems.
Can you describe roughly which script is called with which input? Kind of "workflow"?
I'll probably can figure out by myself, but it would take quite some time ;-)

thanks,
Sven

**Comment by snkeegan** [comment]
Hi Sven,

You can run it without the web server.  The only thing that will not work for you is when viewing the results list, the matching peptides are shown with a link to a program called peptides.pl, which requires a web server to execute (it is a CGI script) and will show you the details of the 'best matching spectrum' for that peptide.  I am not the one who analyzes the results and chooses nanobody candidates for testing, but I know from our colleagues at Rockefeller that this information is helpful in making that choice.

That being said, here is the information.  You can take a look at run_llama_scripts.pl for a general outline of the steps from start to finish.

 To create a database for searching:
1) dnatoprot_longest_nr.pl
- input: fasta file from output of e.g. MiSeq (note, if paired end reads must be merged using a separate tool first); output: protein sequence fasta file
- translates to protein sequences, outputting only the longest non redundant reading frame
  2) digest_fasta.pl
- input: output from the dnatoprot_longest_nr.pl script; output: peptides fasta file
- runs in silico digestion (trypsin) of the protein sequences, necessary for running Tandem search due to the high similarity of nano body sequences

To run the search/mapping of peptides:
1) tandem.exe - the database for searching is the output of step 2 above
2) parse_xtandem_llama.pl
- input: directory of the result file "output.xml" from Tandem run, expectation threshold; output: txt file with extracted information used in step 3 below
- parses Tandem output xml file into txt file containing Tandem results
  3) map_peptides_to_proteins.pl
- input: file from step 2 above, fasta file containing protein sequences (longest_nr.fasta), xml file from Tandem output, 1/0 parameter whether to show the 'score' for a candidate nano body; output: html file containing results of LM algorithm - the candidate nano bodies ranked
- the main LM algorithm - maps peptides back to sequences and finds CDR regions, ranks candidate nano bodies based on coverage of CDR regions, etc.

Let me know if you have any further questions.

Sarah Keegan
sarah@fenyolab.org

**Comment by sklages** [comment]
Hi Sarah,

thanks for your hints. I decided to run run llama-magic "complete", with a webserver.
I see that the github master branch only contains the script files and some other files. But there are no css, js or image files ... is this repo "complete", in terms of "can be installed out-of-the-box"?
Do I miss here something very fundamental? 

best,
Sven

**Comment by sklages** [comment]
Or is there a successor of llama-magic or any other tool you'd recommend?

best,
Sven

**Comment by snkeegan** [comment]
Sorry about that!  I have added the html folder.  You will need to edit "settings.txt" file for your installation, and "add to httpd.txt" contains the information for the "httpd.conf" file, (if you are using Apache.)

**Comment by sklages** [comment]
Hi Sarah,

during testing I uploaded accidentally data on your server.
http://gpmdb.rockefeller.edu/llama-magic-cgi/llama_magic.pl

alpaca_VHH
debug_me

Could you please remove this data from the server as it is not for
public access (yet).

Thanks a lot,
Sven

On Thu, 08 Sep 2016 10:08:57 -0700
snkeegan notifications@github.com wrote:

> Hi Sven,
> 
> You can run it without the web server.  The only thing that will not
> work for you is when viewing the results list, the matching peptides
> are shown with a link to a program called peptides.pl, which requires
> a web server to execute (it is a CGI script) and will show you the
> details of the 'best matching spectrum' for that peptide.  I am not
> the one who analyzes the results and chooses nanobody candidates for
> testing, but I know from our colleagues at Rockefeller that this
> information is helpful in making that choice.
> 
> That being said, here is the information.  You can take a look at
> run_llama_scripts.pl for a general outline of the steps from start to
> finish.
> 
>  To create a database for searching:
> 1) dnatoprot_longest_nr.pl
> - input: fasta file from output of e.g. MiSeq (note, if paired end
>   reads must be merged using a separate tool first); output: protein
>   sequence fasta file
> - translates to protein sequences, outputting only the longest non
>   redundant reading frame 2) digest_fasta.pl
> - input: output from the dnatoprot_longest_nr.pl script; output:
>   peptides fasta file
> - runs in silico digestion (trypsin) of the protein sequences,
>   necessary for running Tandem search due to the high similarity of
>   nano body sequences
> 
> To run the search/mapping of peptides:
> 1) tandem.exe - the database for searching is the output of step 2
> above 2) parse_xtandem_llama.pl
> - input: directory of the result file "output.xml" from Tandem run,
>   expectation threshold; output: txt file with extracted information
>   used in step 3 below
> - parses Tandem output xml file into txt file containing Tandem
>   results 3) map_peptides_to_proteins.pl
> - input: file from step 2 above, fasta file containing protein
>   sequences (longest_nr.fasta), xml file from Tandem output, 1/0
>   parameter whether to show the 'score' for a candidate nano body;
>   output: html file containing results of LM algorithm - the candidate
>   nano bodies ranked
> - the main LM algorithm - maps peptides back to sequences and finds
>   CDR regions, ranks candidate nano bodies based on coverage of CDR
>   regions, etc.
> 
> Let me know if you have any further questions.
> 
> Sarah Keegan
> sarah@fenyolab.org
> 
> ---
> 
> From: sklages [notifications@github.com]
> Sent: Tuesday, September 06, 2016 4:17 AM
> To: FenyoLab/llama-magic
> Subject: [FenyoLab/llama-magic] llama-magic: "workflow" or primer?
> (#1)
> 
> Hi,
> I wanted to use llama-magic without setting up a webserver. I want to
> use it locally on linux systems. Can you describe roughly which
> script is called with which input? Kind of "workflow"? I'll probably
> can figure out by myself, but it would take quite some time ;-)
> 
> thanks,
> Sven
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on
> GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FenyoLab_llama-2Dmagic_issues_1&d=DQMCaQ&c=j5oPpO0eBH1iio48DtsedbOBGmuw5jHLjgvtN2r4ehE&r=PcT9wkmG75ht3wCRmB_AuU1OQ0zcHmOlTgsbIjuf8_o&m=xmmN2dbeZ-ZJ4Et-OQiq7gZP9zq5YXXdd1ZeL9FbeEE&s=6wKYswP7kcix-osqNd2yP7gSHWb_qWMki0R8ZjhZXSQ&e=,
> or mute the
> threadhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACvT9tAYD8mc5MPTU6XLh-5FwzwLPOC75Gks5qnSGKgaJpZM4J1k27&d=DQMCaQ&c=j5oPpO0eBH1iio48DtsedbOBGmuw5jHLjgvtN2r4ehE&r=PcT9wkmG75ht3wCRmB_AuU1OQ0zcHmOlTgsbIjuf8_o&m=xmmN2dbeZ-ZJ4Et-OQiq7gZP9zq5YXXdd1ZeL9FbeEE&s=JxfxHNBXiSrtr5NvLockVPICsk4cq13dnhnAiOrzPQo&e=.
> 
> ---
> 
> This email message, including any attachments, is for the sole use of
> the intended recipient(s) and may contain information that is
> proprietary, confidential, and exempt from disclosure under
> applicable law. Any unauthorized review, use, disclosure, or
> distribution is prohibited. If you have received this email in error
> please notify the sender by return email and delete the original
> message. Please note, the recipient should check this email and any
> attachments for the presence of viruses. The organization accepts no
> liability for any damage caused by any virus transmitted by this
> email. =================================

## 

 Sven  Klages
 Max Planck Institute for Molecular Genetics
 Web : http://www.molgen.mpg.de/SeqTeam

**Comment by snkeegan** [comment]
I have deleted the data.
